### ISSUE TITLE
ESP-ADF Portuguese (AUD-852)

### ISSUE THREAD

**Issue by tcpipchip** [espressif/esp-adf#255] opened 2019-10-05 14:17 UTC
Now, Alexa speaks portuguese (BRAZIL)

How can i enable the ESP-ADF to use the ALEXA portuguese service ?

Thanks!

**Comment by jason-mao** [comment] 2019-10-21 03:05
Closed, this issue duplicate of https://github.com/espressif/esp-va-sdk/issues/65.

**Closed by jason-mao** 2019-10-21 03:05 UTC
